[package]
name = "dux"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]

[dependencies]
log        = "0.3"
env_logger = "0.3"

clap = "2"
xdg  = "2"
toml = "0.1"
dbus = "0.3"

xcb       = { version = "0.7", features = ["randr"] }
xcb-util  = { version = "0.1", features = ["icccm", "ewmh"], path = "../xcb-util" }
byteorder = "0.5"
